package com.gyk.dao;

import com.gyk.po.ReaderInfo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ReaderInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader_info
     *
     * @mbggenerated Tue Mar 30 16:30:04 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader_info
     *
     * @mbggenerated Tue Mar 30 16:30:04 CST 2023
     */
    int insert(ReaderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader_info
     *
     * @mbggenerated Tue Mar 30 16:30:04 CST 2023
     */
    int insertSelective(ReaderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader_info
     *
     * @mbggenerated Tue Mar 30 16:30:04 CST 2023
     */
    ReaderInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader_info
     *
     * @mbggenerated Tue Mar 30 16:30:04 CST 2023
     */
    int updateByPrimaryKeySelective(ReaderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader_info
     *
     * @mbggenerated Tue Mar 30 16:30:04 CST 2023
     */
    int updateByPrimaryKey(ReaderInfo record);

    /**
     * 查询所有记录信息
     */
    List<ReaderInfo> queryAllReaderInfo(ReaderInfo readerInfo);

    /**
     * 根据用户名和密码查询用户信息
     */
    ReaderInfo queryUserInfoByNameAndPassword(@Param("username") String username, @Param("password") String password);
}